#!/usr/bin/env bash
source ./scripts/colors.sh 2>/dev/null;
source ./colors.sh 2>/dev/null;

PATH=$(npm bin):$PATH

if hash $1 2>/dev/null; then
    eval $@
else
    message="You should install ${YELLOW}'$1'${NORMAL} globally or locally (if it's a npm module) and try again."

    case "$1" in
        forever) message="You should install ${YELLOW}'forever'${NORMAL} — ${MAGENTA}npm i forever ${NORMAL}or ${MAGENTA}npm i -g forever"
            ;;
        nodemon) message="You should install ${YELLOW}'nodemon'${NORMAL} — ${MAGENTA}npm i nodemon ${NORMAL}or ${MAGENTA}npm i -g nodemon"
            ;;
    esac

    echo " "
    echo -en "${RED}[ERROR]${NORMAL} ${message} ${NORMAL}"
    echo " "
    echo " "
fi
